services:
  redis:
    image: redis/redis-stack:latest
    container_name: redis-server-dev
    restart: unless-stopped
    ports:
      - "6379:6379"
    volumes:
      - redis_data_dev:/data

  redisinsight:
    image: redis/redisinsight:latest
    container_name: redisinsight-dev
    restart: unless-stopped
    ports:
      - "5540:5540"
    volumes:
      - redisinsight_data_dev:/data

  langgraph:
    build:
      context: .
      dockerfile: Dockerfile.langgraph
    container_name: langgraph-dev
    command: langgraph dev --host=0.0.0.0 --port=2024 --config src/graph/langgraph.json
    ports:
      - "2024:2024"
    volumes:
      - .:/app
    environment:
      - MONGO_URI=mongodb://mongodb:27017
      - ENV=development
    depends_on:
      - redis
      - mongodb
    restart: unless-stopped

  fastapi:
    build:
      context: .
      dockerfile: Dockerfile.fastapi
    container_name: fastapi_server_dev
    command: uvicorn src.api.main:app --host 0.0.0.0 --port 8000 --reload
    ports:
      - "8000:8000"
    volumes:
      - .:/app
    environment:
      - MONGO_URI=mongodb://mongodb:27017
      - ENV=development
    depends_on:
      - redis
      - mongodb
    restart: unless-stopped

  mongodb:
    image: mongo:latest
    container_name: mongodb-dev
    restart: unless-stopped
    ports:
      - "27017:27017"
    volumes:
      - mongo_data_dev:/data/db

  chromadb:
    image: chromadb/chroma:latest
    container_name: chromadb-dev
    environment:
      - CHROMA_SERVER_HOST=0.0.0.0
      - CHROMA_SERVER_PORT=8000
    ports:
      - "8001:8000"
    volumes:
      - chroma_data_dev:/data
    restart: unless-stopped

volumes:
  redis_data_dev:
  redisinsight_data_dev:
  mongo_data_dev:
  chroma_data_dev:
