services:
  redis:
    image: redis/redis-stack:latest
    container_name: redis-server
    restart: always
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data

  redisinsight:
    image: redis/redisinsight:latest
    container_name: redisinsight
    restart: always
    ports:
      - "5540:5540"
    volumes:
      - redisinsight_data:/data

  langgraph:
    build:
      context: .
      dockerfile: Dockerfile.langgraph
    container_name: langgraph
    command: langgraph dev --host=0.0.0.0 --port=2024
    ports:
      - "2024:2024"
    volumes:
      - .:/app
    depends_on:
      - redis
      - mongodb

  fastapi:
    build:
      context: .
      dockerfile: Dockerfile.fastapi
    container_name: fastapi_server
    ports:
      - "8000:8000"
    volumes:
      - .:/app
    depends_on:
      - redis
      - mongodb

  mongodb:
    image: mongo:latest
    container_name: mongodb
    restart: always
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db

volumes:
  redis_data:
  redisinsight_data:
  mongo_data:
