FROM python:3.11-slim

RUN pip install --upgrade pip

WORKDIR /app

COPY requirements.txt .

RUN pip install -r requirements.txt

COPY . /app

ENV PYTHONPATH="/app"

CMD ["langgraph", "dev", "--config", "src/graph/langgraph.json", "--host=0.0.0.0", "--port=2024"]
